name: Deploy Streamlit App

on:
  push:
    branches:
      - main  # This will trigger the workflow on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11.9]  # Specify Python 3.11.9

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Streamlit
      run: |
        streamlit run app.py  # Replace `app.py` with your main Streamlit app script
